INSERT INTO public.genres (id, genre) VALUES (1, '16+');
INSERT INTO public.genres (id, genre) VALUES (2, '18+');
INSERT INTO public.genres (id, genre) VALUES (3, 'Action');
INSERT INTO public.genres (id, genre) VALUES (4, 'Cổ Đại');
INSERT INTO public.genres (id, genre) VALUES (5, 'Adult');
INSERT INTO public.genres (id, genre) VALUES (6, 'Adventure');
INSERT INTO public.genres (id, genre) VALUES (7, 'Anime');
INSERT INTO public.genres (id, genre) VALUES (8, 'Bạo lực - Máu me');
INSERT INTO public.genres (id, genre) VALUES (9, 'Comedy');
INSERT INTO public.genres (id, genre) VALUES (10, 'Comic');
INSERT INTO public.genres (id, genre) VALUES (11, 'Doujinshi');
INSERT INTO public.genres (id, genre) VALUES (12, 'Drama');
INSERT INTO public.genres (id, genre) VALUES (13, 'Ecchi');
INSERT INTO public.genres (id, genre) VALUES (14, 'Event BT');
INSERT INTO public.genres (id, genre) VALUES (15, 'Fantasy');
INSERT INTO public.genres (id, genre) VALUES (16, 'Full màu');
INSERT INTO public.genres (id, genre) VALUES (17, 'Game');
INSERT INTO public.genres (id, genre) VALUES (18, 'Gender Bender');
INSERT INTO public.genres (id, genre) VALUES (19, 'Harem');
INSERT INTO public.genres (id, genre) VALUES (20, 'Historical');
INSERT INTO public.genres (id, genre) VALUES (21, 'Horror');
INSERT INTO public.genres (id, genre) VALUES (22, 'Isekai');
INSERT INTO public.genres (id, genre) VALUES (23, 'Josei');
INSERT INTO public.genres (id, genre) VALUES (24, 'Live action');
INSERT INTO public.genres (id, genre) VALUES (25, 'Magic');
INSERT INTO public.genres (id, genre) VALUES (26, 'Manga');
INSERT INTO public.genres (id, genre) VALUES (27, 'Manhua');
INSERT INTO public.genres (id, genre) VALUES (28, 'Manhwa');
INSERT INTO public.genres (id, genre) VALUES (29, 'Martial Arts');
INSERT INTO public.genres (id, genre) VALUES (30, 'Mature');
INSERT INTO public.genres (id, genre) VALUES (31, 'Mecha');
INSERT INTO public.genres (id, genre) VALUES (32, 'Mystery');
INSERT INTO public.genres (id, genre) VALUES (33, 'Nấu Ăn');
INSERT INTO public.genres (id, genre) VALUES (34, 'Ngôn Tình');
INSERT INTO public.genres (id, genre) VALUES (35, 'NTR');
INSERT INTO public.genres (id, genre) VALUES (36, 'One shot');
INSERT INTO public.genres (id, genre) VALUES (37, 'Psychological');
INSERT INTO public.genres (id, genre) VALUES (38, 'Romance');
INSERT INTO public.genres (id, genre) VALUES (39, 'School Life');
INSERT INTO public.genres (id, genre) VALUES (40, 'Sci-fi');
INSERT INTO public.genres (id, genre) VALUES (41, 'Seinen');
INSERT INTO public.genres (id, genre) VALUES (42, 'Shoujo');
INSERT INTO public.genres (id, genre) VALUES (43, 'Shoujo Ai');
INSERT INTO public.genres (id, genre) VALUES (44, 'Shounen');
INSERT INTO public.genres (id, genre) VALUES (45, 'Shounen Ai');
INSERT INTO public.genres (id, genre) VALUES (46, 'Slice of Life');
INSERT INTO public.genres (id, genre) VALUES (47, 'Smut');
INSERT INTO public.genres (id, genre) VALUES (48, 'Soft Yaoi');
INSERT INTO public.genres (id, genre) VALUES (49, 'Soft Yuri');
INSERT INTO public.genres (id, genre) VALUES (50, 'Sports');
INSERT INTO public.genres (id, genre) VALUES (51, 'Supernatural');
INSERT INTO public.genres (id, genre) VALUES (52, 'Tạp chí truyện tranh');
INSERT INTO public.genres (id, genre) VALUES (53, 'Tragedy');
INSERT INTO public.genres (id, genre) VALUES (54, 'Trap (Crossdressing)');
INSERT INTO public.genres (id, genre) VALUES (55, 'Trinh Thám');
INSERT INTO public.genres (id, genre) VALUES (56, 'Truyện scan');
INSERT INTO public.genres (id, genre) VALUES (57, 'Tu chân - tu tiên');
INSERT INTO public.genres (id, genre) VALUES (58, 'Video Clip');
INSERT INTO public.genres (id, genre) VALUES (59, 'VnComic');
INSERT INTO public.genres (id, genre) VALUES (60, 'Webtoon');
INSERT INTO public.genres (id, genre) VALUES (61, 'Yuri');
