package uet.ppvan.mangareader.utils;


import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.JwtParser;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

import java.security.Key;
import java.time.Duration;
import java.time.Instant;
import java.util.Date;

/**
 * Unity class to handle JWT.
 */
@Component
public class JwtUtils {

    @Value("${jwt.secret-key}")
    private void setSecretKey(String secretKey) {
        JwtUtils.SECRET_KEY = secretKey;
    }

    private static String SECRET_KEY; // default

    @SuppressWarnings("unused")
    public static String generateJWT(Object obj) {
        String json = ValueMapper.objectAsJson(obj);

        return Jwts.builder()
        .setSubject(json)
        .setIssuer("Unknown")
        .setIssuedAt(Date.from(Instant.now()))
        .signWith(getKey())
        .compact();
    }

    /**
     * Generate a JWT string from object.
     * The Object is serialized to JSON then written to JWT as Subject.
     * @param obj The object to generate JWT
     * @param expiredTime Expired time
     * @return JWT have JSON string as Subject claims
     */
    public static String generateJWT(Object obj, Duration expiredTime) {
        String json = ValueMapper.objectAsJson(obj);

        return Jwts.builder()
        .setSubject(json)
        .setIssuer("Unknown")
        .setIssuedAt(Date.from(Instant.now()))
        .setExpiration(Date.from(Instant.now().plus(expiredTime)))
        .signWith(getKey())
        .compact();
    }

    /**
     * Deserialize Object from JWT
     * @param type The class type
     * @param jwt JWT string generated by {@link #generateJWT(Object, Duration)}
     * @return The object with safe-type T
     * @param <T> Object class to map using Jackson
     * @throws ExpiredJwtException if JWT is expired
     * @throws MalformedJwtException if JWT is not valid
     */
    public static <T> T parseJWT(Class<T> type, String jwt) throws ExpiredJwtException, MalformedJwtException {
        var parser = jwtParser();
        var claims = parser.parseClaimsJws(jwt);
        String json = claims.getBody().getSubject();

        return ValueMapper.jsonAsObject(type, json);
    }

    @Bean
    private static Key getKey() {
        return Keys.hmacShaKeyFor(Decoders.BASE64.decode(SECRET_KEY));
    }

    @Bean
    private static JwtParser jwtParser() {
        return Jwts.parserBuilder()
        .setSigningKey(getKey())
        .build();
    }
}
