spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    password: ${DB_PASS:ubuntu}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    url: jdbc:mysql://${DB_NAME:localhost}/mangadb?createDatabaseIfNotExist=true&useSSL=TRUE&serverTimezone=UTC
  h2:
    console:
      enabled: 'true'
server:
  error:
    whitelabel:
      enabled: 'true'
    include-stacktrace: on_param
    include-exception: 'false'
    include-message: always
