spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
  datasource:
    password: ${DB_PASS:ubuntu}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    url: jdbc:mysql://${DB_NAME:localhost}/mangadb?createDatabaseIfNotExist=true&useSSL=TRUE&serverTimezone=UTC
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
server:
  error:
    whitelabel:
      enabled: 'true'
    include-stacktrace: on_param
    include-exception: 'false'
    include-message: always

  tomcat:
    max-swallow-size: 100MB

config:
  drive-folder: ${env.DRIVE_FOLDER}
  host: ${env.DOMAIN_NAME}
  credentials: ${env.CREDENTIALS}
debug: true

